bot:
  name: FirstTestBotDjek
  token: 5343043710:AAGkAzWRTW-uf97voR1YPSSud-UkZRIOtlE
spring:
  datasource:
    url: jdbc:postgresql://ec2-176-34-211-0.eu-west-1.compute.amazonaws.com:5432/d34o8m09u92hfn?user=eeibngczdsjilq&password=82630dd1506def2c938f7aee43781be862c334508fd042206af183101c0010d4
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create