bot_resident:
  name: FirstTestBotDjek
  token: 5343043710:AAGkAzWRTW-uf97voR1YPSSud-UkZRIOtlE
bot_company:
  name: CompanyBot
  token: 5374691537:AAEisTXM_TgdEZ7Wz3pK_QvyGK6sb0UJOqQ
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update