bot:
  name: FirstTestBotDjek
  token: 5343043710:AAGkAzWRTW-uf97voR1YPSSud-UkZRIOtlE
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/ddqo7qlk8tjage?user=ucabivattopzxv&password=2934344f334e3f5261b549d6e1d5ad725cd2725b5a1fa7e87277cb963e5f13f2
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update